// Code generated by "stringer -trimprefix CFCCategory -type CFCCategory"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CFCCategoryInvalid-0]
	_ = x[CFCCategoryRequest-1]
	_ = x[CFCCategoryComplaint-2]
	_ = x[CFCCategoryClaim-3]
	_ = x[CFCCategorySuggestion-4]
}

const _CFCCategory_name = "InvalidRequestComplaintClaimSuggestion"

var _CFCCategory_index = [...]uint8{0, 7, 14, 23, 28, 38}

func (i CFCCategory) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CFCCategory_index)-1 {
		return "CFCCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CFCCategory_name[_CFCCategory_index[idx]:_CFCCategory_index[idx+1]]
}
