// Code generated by "stringer -trimprefix UserRole -type UserRole"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserRoleInvalid-0]
	_ = x[UserRoleManager-1]
	_ = x[UserRoleTeacher-2]
	_ = x[UserRoleStudent-3]
}

const _UserRole_name = "InvalidManagerTeacherStudent"

var _UserRole_index = [...]uint8{0, 7, 14, 21, 28}

func (i UserRole) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UserRole_index)-1 {
		return "UserRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserRole_name[_UserRole_index[idx]:_UserRole_index[idx+1]]
}
