// Code generated by "stringer -type UserGenre"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserGenreInvalid-0]
	_ = x[UserGenreMale-1]
	_ = x[UserGenreFemale-2]
	_ = x[UserGenreOther-3]
}

const _UserGenre_name = "UserGenreInvalidUserGenreMaleUserGenreFemaleUserGenreOther"

var _UserGenre_index = [...]uint8{0, 16, 29, 44, 58}

func (i UserGenre) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UserGenre_index)-1 {
		return "UserGenre(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserGenre_name[_UserGenre_index[idx]:_UserGenre_index[idx+1]]
}
